import { Geist, Geist_Mono, Lora, Amaranth, Questrial } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistLora = Lora({
  variable: "--font-geist-lora",
  subsets: ["latin"],
});
const amaranth = Amaranth({
  subsets: ["latin"], 
  weight: ["400", "700"],
  variable: "--font-amaranth", 
});

const questrial = Questrial({
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-questrial",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistLora.variable} ${amaranth.variable} ${questrial.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
